### ISSUE TITLE
Determine what development stack we're going to use

### ISSUE THREAD

**Issue by robmaceachern** [robmaceachern/cpsc304#1]
We need to decide what we're going to be using to implement the last part of the project. A few options:

Database:
- MySql
- Postgres
- UBC's Oracle setup

Application code:
- java (jdbc to connect to db, tomcat as web server for web app)
- c/c++ (I can't remember the name... ODBC?) 
- php
- other (python, RoR, Haskell, Prolog ;)

GUI:
- web application
- desktop java application (swing, awt)
- mobile app (?)

**Comment by robmaceachern** [comment]
I'm leaning towards a MySql -> Java (jdbc and tomcat) -> Web app. I think it'd be relatively straightforward to setup and there would be lots of documentation available for each piece if we ran into trouble.

**Comment by rc9** [comment]
prolog for sure.  and we'll create our own DBMS for it to boot and just shame everyone

**Comment by robmaceachern** [comment]
Okie so MySQL, Java (JDBC and Tomcat), and a web app win. GET READY TO ROCK!!!
