### ISSUE TITLE
Make some UI mockups

### ISSUE THREAD

**Issue by robmaceachern** [robmaceachern/cpsc304#3]
Go through the requirements and design mockups for the key UI elements.

**Comment by rc9** [comment]
PART 3
http://www.ugrad.cs.ubc.ca/~cs304/2011W1/project/p3/p3-desc.html

just so we can't quickly jump over to the overview.

**Comment by robmaceachern** [comment]
i made some mockups for librarian stuff.

assigning to robert. If you don't want to make mockups for your section that's fine, just pass it on to riley.
