### ISSUE TITLE
Make database tables

### ISSUE THREAD

**Issue by rc9** [robmaceachern/cpsc304#4]
Create the schema of the tables for the db. 

Should these be based on ours or the answer key to assignment 2?
I think as far as the tables go we matched pretty well.

**Comment by rc9** [comment]
Nevermind, tables we need are defined for us. How handy :]

**Comment by rc9** [comment]
So I created the schema for our db, but it kept throwing an errno 121 if I tried to include copyNo as a foreign key in the Borrowing table.  I have no idea why this is happening.  I changed it at one point but then it wouldn't accept the BookCopy table.  Maybe one of you guys know?

Other than that the table is good to go.

**Comment by robmaceachern** [comment]
Take a look at my commit https://github.com/robmaceachern/cpsc304/commit/7fb3c688227daace85fc59d76b5d5c6e1fdc013a

If this looks good you can close this.

**Comment by rc9** [comment]
if that works I'd say it's good to close.
I found another way to make it too, but I don't understand why my new way works when the other one didn't.  I prefer this fix.

**Comment by robmaceachern** [comment]
Yeah it seems to work fine for me. Give it a go and try it out too.

Rob MacEachern
(778) 938-1066

On Sat, Nov 19, 2011 at 12:54 PM, rc9 <
reply@reply.github.com
